import React, { useState } from 'react';
import { RepoInfo, AnalysisResult, FileContent } from '../types';
import { DownloadIcon, ShieldCheckIcon, ContentCard, Badge, SecurityItem, MermaidDiagram, MarkdownRenderer } from './SharedUI';
import { FileExplorer } from './FileExplorer';

interface AnalysisReportProps {
  repoInfo: RepoInfo;
  analysis: AnalysisResult;
  structure: string[];
  files: FileContent[];
}

export const AnalysisReport: React.FC<AnalysisReportProps> = ({ repoInfo, analysis, structure, files }) => {
  const [activeDiagram, setActiveDiagram] = useState<'class' | 'seq'>('class');
  
  const handleDownload = () => {
    const markdown = `
# ${repoInfo.owner}/${repoInfo.name} - AI Analysis
*Generated by CodePulse AI*

## Summary
${analysis.summary}

## Tech Stack
${analysis.techStack.map(t => `- ${t}`).join('\n')}

## Key Components
${analysis.keyComponents.map(c => `- ${c}`).join('\n')}

## Installation
${analysis.installation}

## Security & Quality
Summary: ${analysis.securityProfile}

Vulnerabilities:
${analysis.vulnerabilities?.map(v => `- [${v.severity}] ${v.title}: ${v.description}`).join('\n') || "None detected."}

## Developer Notes
${analysis.notes}
    `;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${repoInfo.name}-analysis.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
     <div className="space-y-8 animate-fade-in-up">
        {/* Repo Header Info */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-6 border-b border-gray-200 dark:border-github-border">
        <div>
          <a href={repoInfo.url} target="_blank" rel="noreferrer" className="text-2xl font-bold text-blue-600 dark:text-github-accent hover:underline break-all">
            {repoInfo.owner}/{repoInfo.name}
          </a>
          <p className="text-gray-600 dark:text-gray-400 mt-1 text-lg">{repoInfo.description || "No description provided."}</p>
        </div>
        <div className="flex flex-col items-end gap-2 shrink-0">
          <div className="flex items-center gap-6 text-sm text-gray-500 dark:text-gray-400">
            <div className="flex items-center gap-1">
              <svg className="w-5 h-5 text-yellow-500" fill="currentColor" viewBox="0 0 20 20">
                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
              </svg>
              <span>{repoInfo.stars.toLocaleString()}</span>
            </div>
            <div className="flex items-center gap-1">
              <span className="w-3 h-3 rounded-full bg-green-600 dark:bg-github-button inline-block"></span>
              <span>{repoInfo.language || 'Unknown'}</span>
            </div>
            <div className="flex items-center gap-1">
              <svg className="w-5 h-5 text-gray-400 dark:text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 20l4-16m2 16l4-16M6 9h14M4 15h14" /></svg>
              <span>{repoInfo.defaultBranch}</span>
            </div>
          </div>
          
          <button 
            onClick={handleDownload}
            className="flex items-center gap-2 px-3 py-1.5 bg-white dark:bg-github-card hover:bg-gray-100 dark:hover:bg-gray-800 border border-gray-300 dark:border-github-border rounded text-sm text-gray-700 dark:text-gray-300 transition-colors shadow-sm dark:shadow-none"
          >
            <DownloadIcon />
            Export MD
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Main Content (Left 2 cols) */}
        <div className="lg:col-span-2 space-y-8">
          
          <ContentCard title="System Diagrams" collapsible>
            <div className="flex gap-2 mb-4 border-b border-gray-200 dark:border-github-border pb-1">
               <button 
                  onClick={() => setActiveDiagram('class')}
                  className={`px-3 py-1 text-sm rounded-t-md border-t border-l border-r ${activeDiagram === 'class' ? 'bg-gray-100 dark:bg-[#0d1117] border-gray-200 dark:border-github-border text-gray-900 dark:text-white font-medium' : 'border-transparent text-gray-500 hover:text-gray-700 dark:hover:text-gray-300'}`}
               >
                 Class Diagram
               </button>
               <button 
                  onClick={() => setActiveDiagram('seq')}
                  className={`px-3 py-1 text-sm rounded-t-md border-t border-l border-r ${activeDiagram === 'seq' ? 'bg-gray-100 dark:bg-[#0d1117] border-gray-200 dark:border-github-border text-gray-900 dark:text-white font-medium' : 'border-transparent text-gray-500 hover:text-gray-700 dark:hover:text-gray-300'}`}
               >
                 Sequence Flow
               </button>
            </div>

            <div className="flex justify-center bg-gray-50 dark:bg-[#0d1117] p-2 rounded border border-gray-200 dark:border-github-border min-h-[200px]">
               {activeDiagram === 'class' && (
                 analysis.classDiagram ? <MermaidDiagram chart={analysis.classDiagram} /> : <div className="text-gray-500 italic p-10">No class diagram generated.</div>
               )}
               {activeDiagram === 'seq' && (
                 analysis.sequenceDiagram ? <MermaidDiagram chart={analysis.sequenceDiagram} /> : <div className="text-gray-500 italic p-10">No sequence diagram generated.</div>
               )}
            </div>
            <p className="text-xs text-center text-gray-500 mt-2">
               {activeDiagram === 'class' ? 'Key classes and interface relationships.' : 
                'Typical control flow sequence.'}
            </p>
          </ContentCard>

          <ContentCard title="Project Summary" collapsible>
            <p className="leading-relaxed text-gray-800 dark:text-gray-200 text-lg">
              {analysis.summary}
            </p>
          </ContentCard>

          <ContentCard title="Installation & Usage" collapsible>
             <div className="p-4 bg-gray-50 dark:bg-github-dark/50 rounded-lg border border-gray-100 dark:border-transparent">
                <MarkdownRenderer content={analysis.installation} />
             </div>
          </ContentCard>
          
           <ContentCard title="Developer Notes" collapsible>
            <p className="leading-relaxed whitespace-pre-line text-gray-700 dark:text-gray-300">
              {analysis.notes}
            </p>
          </ContentCard>
        </div>

        {/* Sidebar (Right 1 col) */}
        <div className="space-y-8">
          <ContentCard title="Tech Stack">
            <div className="flex flex-wrap">
              {analysis.techStack.length > 0 ? (
                analysis.techStack.map((tech, i) => <Badge key={i} text={tech} />)
              ) : (
                <span className="text-gray-500 italic">No specific tech stack detected.</span>
              )}
            </div>
          </ContentCard>

          <ContentCard title="Key Components">
            <ul className="space-y-2">
              {analysis.keyComponents.map((comp, i) => (
                <li key={i} className="flex items-start gap-2 text-sm text-gray-700 dark:text-gray-300">
                   <svg className="w-5 h-5 text-blue-500 dark:text-github-accent shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" /></svg>
                   <span>{comp}</span>
                </li>
              ))}
            </ul>
          </ContentCard>

          <ContentCard title="Security & Code Quality" className="border-l-4 border-l-blue-600">
            <div className="mb-4">
              <p className="text-sm text-gray-600 dark:text-gray-300 mb-2 leading-relaxed italic border-b border-gray-200 dark:border-github-border pb-3">
                 {analysis.securityProfile || "General security assessment."}
              </p>
            </div>
            
            {analysis.vulnerabilities && analysis.vulnerabilities.length > 0 ? (
               <div className="space-y-2">
                 <h4 className="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-2">Detected Issues</h4>
                 {analysis.vulnerabilities.map((vuln, i) => (
                   <SecurityItem key={i} vuln={vuln} />
                 ))}
               </div>
            ) : (
               <div className="flex items-center gap-2 text-green-700 dark:text-green-400 text-sm bg-green-50 dark:bg-green-900/10 border border-green-200 dark:border-green-900/30 p-3 rounded">
                  <ShieldCheckIcon />
                  <span>No high-risk vulnerabilities detected in scanned files.</span>
               </div>
            )}
          </ContentCard>
        </div>

        {/* File Explorer */}
        <div className="col-span-1 lg:col-span-3">
          <FileExplorer repoInfo={repoInfo} structure={structure} files={files} />
        </div>
      </div>
     </div>
  );
};

// Made with Bob
