import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { RepoInfo, AnalysisResult, FileContent } from '../types';
import { DownloadIcon, ShieldCheckIcon, ContentCard, Badge, SecurityItem, MermaidDiagram, MarkdownRenderer } from './SharedUI';
import { FileExplorer } from './FileExplorer';
import { Star, GitBranch, Terminal, Shield, Cpu, Layout, FileText, Download } from 'lucide-react';

interface AnalysisReportProps {
  repoInfo: RepoInfo;
  analysis: AnalysisResult;
  structure: string[];
  files: FileContent[];
}

export const AnalysisReport: React.FC<AnalysisReportProps> = ({ repoInfo, analysis, structure, files }) => {
  const [activeDiagram, setActiveDiagram] = useState<'class' | 'seq'>('class');
  
  const handleDownload = () => {
    const markdown = `
# ${repoInfo.owner}/${repoInfo.name} - AI Analysis
*Generated by CodePulse AI*

## Summary
${analysis.summary}

## Tech Stack
${analysis.techStack.map(t => `- ${t}`).join('\n')}

## Key Components
${analysis.keyComponents.map(c => `- ${c}`).join('\n')}

## Installation
${analysis.installation}

## Security & Quality
Summary: ${analysis.securityProfile}

Vulnerabilities:
${analysis.vulnerabilities?.map(v => `- [${v.severity}] ${v.title}: ${v.description}`).join('\n') || "None detected."}

## Developer Notes
${analysis.notes}
    `;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${repoInfo.name}-analysis.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: { opacity: 1, transition: { staggerChildren: 0.1 } }
  };

  const cardVariants = {
    hidden: { opacity: 0, y: 15 },
    visible: { opacity: 1, y: 0, transition: { type: 'spring', stiffness: 100, damping: 15 } }
  };

  return (
     <motion.div 
       className="space-y-8"
       variants={containerVariants}
       initial="hidden"
       animate="visible"
     >
      {/* Repo Header Info Banner */}
      <motion.div 
        variants={cardVariants}
        className="flex flex-col md:flex-row md:items-center justify-between gap-6 pb-6 border-b border-gray-200 dark:border-github-border/70"
      >
        <div className="space-y-2">
          <div className="flex items-center gap-3 flex-wrap">
            <a 
              href={repoInfo.url} 
              target="_blank" 
              rel="noreferrer" 
              className="text-3xl font-extrabold bg-gradient-to-r from-cyan-600 to-blue-600 dark:from-cyan-400 dark:to-blue-500 text-transparent bg-clip-text hover:underline break-all"
            >
              {repoInfo.owner}/{repoInfo.name}
            </a>
            <span className="px-2.5 py-0.5 text-xs font-semibold rounded-full bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-350 border border-slate-200 dark:border-slate-800">
              public
            </span>
          </div>
          <p className="text-gray-600 dark:text-slate-400 text-base max-w-3xl leading-relaxed">{repoInfo.description || "No description provided."}</p>
        </div>
        
        <div className="flex flex-col sm:flex-row md:flex-col items-start sm:items-center md:items-end gap-3 shrink-0">
          <div className="flex items-center gap-4 text-sm text-gray-500 dark:text-gray-400">
            <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-gray-50 dark:bg-gray-800/40 border border-gray-200/50 dark:border-gray-850">
              <Star className="w-4 h-4 text-amber-500 fill-amber-500" />
              <span className="font-bold text-gray-700 dark:text-gray-300">{repoInfo.stars.toLocaleString()}</span>
            </div>
            <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-gray-50 dark:bg-gray-800/40 border border-gray-200/50 dark:border-gray-850">
              <span className="w-2.5 h-2.5 rounded-full bg-cyan-500 inline-block animate-pulse"></span>
              <span className="font-semibold text-gray-700 dark:text-gray-300">{repoInfo.language || 'Codebase'}</span>
            </div>
            <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-gray-50 dark:bg-gray-800/40 border border-gray-200/50 dark:border-gray-850">
              <GitBranch className="w-4 h-4 text-slate-400" />
              <span className="font-semibold text-gray-700 dark:text-gray-300">{repoInfo.defaultBranch}</span>
            </div>
          </div>
          
          <motion.button 
            onClick={handleDownload}
            className="w-full sm:w-auto flex items-center justify-center gap-2 px-4 py-2 bg-white dark:bg-github-card hover:bg-slate-50 dark:hover:bg-slate-800 border border-slate-200 dark:border-github-border rounded-xl text-sm font-semibold text-slate-700 dark:text-slate-300 transition-colors shadow-sm"
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
          >
            <Download className="w-4 h-4 text-cyan-500" />
            <span>Export Report (Markdown)</span>
          </motion.button>
        </div>
      </motion.div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Main Content Pane (Left 2 columns) */}
        <div className="lg:col-span-2 space-y-8">
          
          <motion.div variants={cardVariants}>
            <ContentCard title="System Architecture Diagrams" collapsible>
              <div className="flex gap-2 mb-5 border-b border-slate-200 dark:border-slate-800/80 pb-0.5">
                 <button 
                    onClick={() => setActiveDiagram('class')}
                    className={`px-4 py-2 text-sm font-semibold rounded-t-xl border-t border-l border-r -mb-px transition-colors ${activeDiagram === 'class' ? 'bg-slate-50 dark:bg-[#0d1117]/60 border-slate-200 dark:border-slate-800/80 text-cyan-600 dark:text-cyan-400' : 'border-transparent text-slate-400 hover:text-slate-600 dark:hover:text-slate-200'}`}
                 >
                   Class Diagram & Interfaces
                 </button>
                 <button 
                    onClick={() => setActiveDiagram('seq')}
                    className={`px-4 py-2 text-sm font-semibold rounded-t-xl border-t border-l border-r -mb-px transition-colors ${activeDiagram === 'seq' ? 'bg-slate-50 dark:bg-[#0d1117]/60 border-slate-200 dark:border-slate-800/80 text-cyan-600 dark:text-cyan-400' : 'border-transparent text-slate-400 hover:text-slate-600 dark:hover:text-slate-200'}`}
                 >
                   Sequence Control Flow
                 </button>
              </div>

              <div className="rounded-xl overflow-hidden shadow-inner bg-slate-50/50 dark:bg-slate-900/10 p-2">
                 <AnimatePresence mode="wait">
                   <motion.div
                     key={activeDiagram}
                     initial={{ opacity: 0, y: 10 }}
                     animate={{ opacity: 1, y: 0 }}
                     exit={{ opacity: 0, y: -10 }}
                     transition={{ duration: 0.2 }}
                   >
                     {activeDiagram === 'class' && (
                       analysis.classDiagram ? <MermaidDiagram chart={analysis.classDiagram} /> : <div className="text-slate-400 italic p-12 text-center text-sm">No class diagram generated.</div>
                     )}
                     {activeDiagram === 'seq' && (
                       analysis.sequenceDiagram ? <MermaidDiagram chart={analysis.sequenceDiagram} /> : <div className="text-slate-400 italic p-12 text-center text-sm">No sequence diagram generated.</div>
                     )}
                   </motion.div>
                 </AnimatePresence>
              </div>
              <p className="text-xs text-center text-slate-450 mt-3 flex items-center justify-center gap-1.5">
                 <Layout className="w-3.5 h-3.5" />
                 <span>{activeDiagram === 'class' ? 'Class diagram maps files, types, and system interface boundaries.' : 'Sequence diagram tracks control flow propagation.'}</span>
              </p>
            </ContentCard>
          </motion.div>

          <motion.div variants={cardVariants}>
            <ContentCard title="AI Project Summary" collapsible>
              <p className="leading-relaxed text-slate-700 dark:text-slate-300 text-base font-normal">
                {analysis.summary}
              </p>
            </ContentCard>
          </motion.div>

          <motion.div variants={cardVariants}>
            <ContentCard title="Installation & Executing Guide" collapsible>
              <div className="p-4 bg-slate-50 dark:bg-slate-950/20 rounded-xl border border-slate-100 dark:border-slate-900/30">
                 <MarkdownRenderer content={analysis.installation} />
              </div>
            </ContentCard>
          </motion.div>
          
          <motion.div variants={cardVariants}>
             <ContentCard title="Technical Developer Notes" collapsible>
              <p className="leading-relaxed whitespace-pre-line text-slate-700 dark:text-slate-300 text-sm font-normal">
                {analysis.notes}
              </p>
            </ContentCard>
          </motion.div>
        </div>

        {/* Sidebar Info Panel (Right 1 column) */}
        <div className="space-y-8">
          
          <motion.div variants={cardVariants}>
            <ContentCard title="Technologies & Frameworks">
              <div className="flex flex-wrap p-1">
                {analysis.techStack.length > 0 ? (
                  analysis.techStack.map((tech, i) => <Badge key={i} text={tech} />)
                ) : (
                  <span className="text-slate-400 italic text-sm">No stack identified.</span>
                )}
              </div>
            </ContentCard>
          </motion.div>

          <motion.div variants={cardVariants}>
            <ContentCard title="System Components">
              <ul className="space-y-3">
                {analysis.keyComponents.map((comp, i) => (
                  <li key={i} className="flex items-start gap-2.5 text-sm text-slate-700 dark:text-slate-300">
                     <Cpu className="w-5 h-5 text-cyan-500 shrink-0 mt-0.5" />
                     <span className="font-medium leading-tight">{comp}</span>
                  </li>
                ))}
              </ul>
            </ContentCard>
          </motion.div>

          <motion.div variants={cardVariants}>
            <ContentCard title="Security & Compliance Audit" className="border-l-4 border-l-cyan-500 shadow-md">
              <div className="mb-4">
                <p className="text-xs text-slate-500 dark:text-slate-400 mb-2 leading-relaxed italic border-b border-slate-100 dark:border-slate-800/80 pb-3">
                   {analysis.securityProfile || "General codebase quality review."}
                </p>
              </div>
              
              {analysis.vulnerabilities && analysis.vulnerabilities.length > 0 ? (
                 <div className="space-y-2">
                   <h4 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-2.5">Identified Risks</h4>
                   {analysis.vulnerabilities.map((vuln, i) => (
                     <SecurityItem key={i} vuln={vuln} />
                   ))}
                 </div>
              ) : (
                 <div className="flex items-center gap-2.5 text-green-700 dark:text-green-400 text-xs bg-green-50 dark:bg-green-950/15 border border-green-200 dark:border-green-900/30 p-4 rounded-xl">
                    <ShieldCheckIcon />
                    <span className="font-medium">No critical dependency risks identified.</span>
                 </div>
              )}
            </ContentCard>
          </motion.div>
        </div>

        {/* Bottom File Explorer */}
        <motion.div variants={cardVariants} className="col-span-1 lg:col-span-3">
          <FileExplorer repoInfo={repoInfo} structure={structure} files={files} />
        </motion.div>
      </div>
     </motion.div>
  );
};
